---
- hosts: dev
  become: yes
  tasks:
    - name: install the pip module
      yum:
        name: python-pip
        state: present
    - name: install the python py module
      pip:
        name: docker-py
        state: present
    - name: install the docker
      yum:
        name: docker
        state: present
    - name: start the docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: start the container
      docker_container:
        name: myappnow2021
        image: "pnkr5454/myapp01:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:9090:8080
          - name: Remove a volume
      docker_volume:
        name: volume_one
        state: present  
    - name: discard the docker images 
      command: docker image prune -a -f --filter 'label=app=my-app' 
      ignore_errors: yes





